experiment_num: 1
dataset: gleason-grading

encoder: uni
num_classes: 5
precision: full
freeze_encoder: true
embedding_mode: true

seed: 42
epochs: 50
batch_size: 100
eta_min: 1.0e-6
weight_decay: 0.0
learning_rate: 1.0e-4