batch_size: 100
dataset: gleason-grading
embedding_mode: true
encoder: uni
epochs: 50
eta_min: 1.0e-06
experiment_num: 0
freeze_encoder: true
learning_rate: 0.0001
num_classes: 5
precision: full
weight_decay: 0.0
